naver:
  id: ccfm_official
  pw: tkach212@!@
  cid: '3301663'
  target_url: https://dev.picory.com/api/token
telegram:
  token: 6845389312:AAGR3427NVNZVU0BmcJr8MZbVSW1TLPqvlA
  chat_id: '-4686863649'
